#!/bin/bash
# 一键部署脚本

echo "🚀 AI 日报系统部署指南"
echo ""
echo "======================================"
echo "📁 项目文件已准备好"
echo "======================================"
echo ""
echo "下一步操作："
echo ""
echo "1️⃣  在 GitHub 创建新仓库"
echo "    https://github.com/new"
echo ""
echo "2️⃣  上传项目文件到仓库"
echo ""
echo "3️⃣  配置 Secrets（复制以下内容）"
echo ""
echo "    进入: Settings → Secrets and variables → Actions"
echo "    点击: New repository secret"
echo ""
echo "----------------------------------------"
echo "Secret 名称                值"
echo "----------------------------------------"
echo "EMAIL_SMTP_SERVER          smtp.163.com"
echo "EMAIL_SMTP_PORT            465"
echo "EMAIL_USERNAME             18973490188@163.com"
echo "EMAIL_PASSWORD             ALdXTGM7CcAj78KH"
echo "EMAIL_TO                   18973490188@163.com"
echo "EMAIL_USE_SSL              true"
echo "----------------------------------------"
echo ""
echo "4️⃣  测试运行"
echo "    进入 Actions → AI Daily News → Run workflow"
echo ""
echo "⏰ 自动执行时间: 每天北京时间 9:30"
echo ""
